language: php
dist: trusty
php:
  - 7.2
  - 7.3
  - 7.4

env:
  - LOWEST_VERSIONS=""
  - LOWEST_VERSIONS=--prefer-lowest

sudo: false

install: travis_retry composer update $LOWEST_VERSIONS

script: composer ci

cache:
  directories:
    - $HOME/.composer/cache
