language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

sudo: false

install:
  - travis_retry composer update
  - travis_retry composer update --prefer-lowest

script: composer ci

cache:
  directories:
    - $HOME/.composer/cache
